### ISSUE TITLE
some problem when using the lib

### ISSUE THREAD

**Issue by Nerom** [evanplaice/node-ftpsync#10]
when I use `new` keyword to create a ftpsync object , I get an error.

so , I don't use that way to get a ftpsync object,and let my object equal the `ftpsync` required from your module.
but when I use the `ftpsync.run ` , It goes on to `commit` function, I get an error as below:
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write ECONNRESET
    at errnoException (net.js:901:11)
    at Object.afterWrite (net.js:718:19)
```
and I can't solve the problem , can you give me some idea? @evanplaice

**Comment by bahadircyildiz** [comment]
Hey, I'm having the same problem. Can you share how did you solve it?
