### ISSUE TITLE
ftpsync stops uploading after x files

### ISSUE THREAD

**Issue by gernmehr** [evanplaice/node-ftpsync#30]
When I try uploading a folder and some files to my FTP-Server, it stops uploading after x files every time (always after the same amount of files). Any ideas, what the problem can be?
![node-ftpsync](https://cloud.githubusercontent.com/assets/2779209/13537839/5bf110aa-e247-11e5-9c66-8d5eb776b019.JPG)

**Comment by evanplaice** [comment]
This appears to be an issue with an older version of JSFTP. The dependency was updated with PR #39.
