### ISSUE TITLE
Cannot sync all files of a folder

### ISSUE THREAD

**Issue by sotoremydocuments** [evanplaice/node-ftpsync#38]
Hi,

Thank for your awesome ftp nodejs.
This nodejs module cannot download all files of a folder which contains more than 1000 files.
It can only download 300-700 files at one times

**Comment by jppellerin** [comment]
This project seems to have been abandonned by the owner...

I have a pull request that might fix your issue #39 .

Bascially, I think that jsftp fixed the issue, and updating that library is the solution.  You can give that a try.
