### ISSUE TITLE
Error: 550 Create directory operation failed

### ISSUE THREAD

**Issue by jjude** [evanplaice/node-ftpsync#5]
Hi,
I get the below error when I sync with a remote server. 
MKDIR failed.
MKDIRs failed.
Commit failed.

I thought it might be permission issues but I connected using ftp with the same userid and password and I was able to create directories and remove directories. When I enable verbose logging, it lists the files in the remote directory.

What could be the issue here, and how do I go about troubleshot and fix?

Thank you,
Joseph

**Comment by evanplaice** [comment]
This issue should be resolved now as documented in #22.

A bug in jsftp was the source of the problem. It has been patched recently to fix the issue. Be sure to pull the latest and update your dependencies.
