### ISSUE TITLE
Error on removing files with accent (like é) during sync operation on ftp

### ISSUE THREAD

**Issue by jmzoda** [evanplaice/node-ftpsync#9]
Didn't check with accents on directories but discovered errors on removing files with accent (like é) during sync operation on ftp. Copying without any troubles but removing files with accent on ftp gives : 550 File not found error.

See extract of ftpsync + ftp server logs below for more details : 
''
'Consolidating'
'-------------------------------------------------------------'
'Mkdir:'
[]
''
'Rmdir:'
[]
''
'Add:'
[ '/HOME-abonnés.jpg' ]
''
'Updates:'
[]
''
'Remove:'
[ '/HOME-abonnÃ©s.jpg' ]
''
>> Consolidation complete.
''
'Committing'
'-------------------------------------------------------------'
'-'
>> Additions complete.
>> Remove failed.
>> Removals failed.
>> Commit failed.
>> Commit complete.
>> Removals complete
'-'
Warning: 550 File not found Use --force to continue.
Aborted due to warnings.

Ftp shows : 
> 230 Logged on
> type I
> 200 Type set to I
> pasv
> 227 Entering Passive Mode (...)
> stor /HOME-abonnés.jpg
> 150 Opening data channel for file upload to server of "/HOME-abonnés.jpg"
> 226 Successfully transferred "/HOME-abonnés.jpg"
> dele /HOME-abonnÃ©s.jpg
> 550 File not found
> disconnected.

Thanks in advance

**Comment by jmzoda** [comment]
Error coming from file parser.js in jsftp.js in ftpsync.js. 
Fixed it locally and made a pull request.

**Comment by evanplaice** [comment]
Currently waiting for a response. If it has been fixed I'll update the dependencies to the latest.

**Comment by jmzoda** [comment]
Not currently fixed. It is has not been updated on the master branch of jsftp. 
Unfortunately my issue is still open : https://github.com/sergi/jsftp/issues/121

**Comment by evanplaice** [comment]
@jmzoda Thanks for the update.

**Comment by jmzoda** [comment]
@evanplaice Don't hesitate. You are welcome.

**Comment by flyinhigh** [comment]
command not found: ftpsync

**Comment by evanplaice** [comment]
@jmzoda I just finished updating all the dependencies. JSFTP is has been bumped to the latest including the commit that fixed this issue.

I'm going to close for now, let me know if you run into any more issues.
